packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  msw: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - sharp
  - unrs-resolver
