import { Chat } from '../messenger.types'

export const MOCK_CHATS: Chat[] = [
  {
    id: 'chat-1',
    userId: 1,
    username: 'John Doe',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-1',
    lastMessage: 'Hey, how is it going?',
    lastMessageTimestamp: '10:30 AM',
  },
  {
    id: 'chat-2',
    userId: 2,
    username: 'Jane Smith',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-2',
    lastMessage: 'Can you check the Figma design?',
    lastMessageTimestamp: 'Yesterday',
  },
  {
    id: 'chat-3',
    userId: 3,
    username: 'Alice Johnson',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-3',
    lastMessage: 'I sent you the files',
    lastMessageTimestamp: 'Monday',
  },
  {
    id: 'chat-4',
    userId: 4,
    username: 'Bob Brown',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-4',
    lastMessage: 'Meeting at 5?',
    lastMessageTimestamp: '2 hours ago',
  },
  {
    id: 'chat-5',
    userId: 5,
    username: 'Charlie Davis',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-5',
    lastMessage: 'The report is ready',
    lastMessageTimestamp: 'Yesterday',
  },
  {
    id: 'chat-6',
    userId: 6,
    username: 'Diana Prince',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-6',
    lastMessage: 'Did you see the news?',
    lastMessageTimestamp: 'Wednesday',
  },
  {
    id: 'chat-7',
    userId: 7,
    username: 'Ethan Hunt',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-7',
    lastMessage: 'Mission accomplished',
    lastMessageTimestamp: 'Friday',
  },
  {
    id: 'chat-8',
    userId: 8,
    username: 'Fiona Glenanne',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-8',
    lastMessage: 'Check your email',
    lastMessageTimestamp: 'Last week',
  },
]
