import { Message, Chat } from './messenger.types'

export const MOCK_CHATS: Chat[] = [
  {
    id: 'chat-1',
    userId: 'user-1',
    username: 'John Doe',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-1',
    lastMessage: 'Hey, how is it going?',
    lastMessageTimestamp: '10:30 AM',
  },
  {
    id: 'chat-2',
    userId: 'user-2',
    username: 'Jane Smith',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-2',
    lastMessage: 'Can you check the Figma design?',
    lastMessageTimestamp: 'Yesterday',
  },
  {
    id: 'chat-3',
    userId: 'user-3',
    username: 'Alice Johnson',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-3',
    lastMessage: 'I sent you the files',
    lastMessageTimestamp: 'Monday',
  },
  {
    id: 'chat-4',
    userId: 'user-4',
    username: 'Bob Brown',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-4',
    lastMessage: 'Meeting at 5?',
    lastMessageTimestamp: '2 hours ago',
  },
  {
    id: 'chat-5',
    userId: 'user-5',
    username: 'Charlie Davis',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-5',
    lastMessage: 'The report is ready',
    lastMessageTimestamp: 'Yesterday',
  },
  {
    id: 'chat-6',
    userId: 'user-6',
    username: 'Diana Prince',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-6',
    lastMessage: 'Did you see the news?',
    lastMessageTimestamp: 'Wednesday',
  },
  {
    id: 'chat-7',
    userId: 'user-7',
    username: 'Ethan Hunt',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-7',
    lastMessage: 'Mission accomplished',
    lastMessageTimestamp: 'Friday',
  },
  {
    id: 'chat-8',
    userId: 'user-8',
    username: 'Fiona Glenanne',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-8',
    lastMessage: 'Check your email',
    lastMessageTimestamp: 'Last week',
  },
]

export const MOCK_MESSAGES: Record<string, Message[]> = {
  'user-1': [
    { id: 'm1', text: 'Hi there!', senderId: 'user-1', timestamp: '10:00 AM', type: 'text' },
    { id: 'm2', text: 'How are you doing?', senderId: 'me', timestamp: '10:01 AM', type: 'text' },
    {
      id: 'm3',
      text: 'I am doing great, thanks for asking!',
      senderId: 'user-1',
      timestamp: '10:05 AM',
      type: 'text',
    },
    {
      id: 'm4',
      text: 'Hey, how is it going?',
      senderId: 'user-1',
      timestamp: '10:30 AM',
      type: 'text',
    },
  ],
  'user-2': [
    { id: 'm5', text: 'Hello!', senderId: 'user-2', timestamp: '9:00 AM', type: 'text' },
    {
      id: 'm6',
      text: 'Did you see the latest update?',
      senderId: 'me',
      timestamp: '9:05 AM',
      type: 'text',
    },
    {
      id: 'm7',
      text: 'Yes, it looks awesome!',
      senderId: 'user-2',
      timestamp: '9:10 AM',
      type: 'text',
    },
    {
      id: 'm8',
      text: 'Can you check the Figma design?',
      senderId: 'user-2',
      timestamp: 'Yesterday',
      type: 'text',
    },
  ],
  'user-3': [
    { id: 'm9', text: 'Hey!', senderId: 'user-3', timestamp: '8:00 AM', type: 'text' },
    {
      id: 'm10',
      text: 'I sent you the files',
      senderId: 'user-3',
      timestamp: 'Monday',
      type: 'text',
    },
  ],
  'user-4': [
    { id: 'u4-m1', text: 'Hey Bob!', senderId: 'me', timestamp: '11:00 AM', type: 'text' },
    {
      id: 'u4-m2',
      text: 'How is the project?',
      senderId: 'user-4',
      timestamp: '11:05 AM',
      type: 'text',
    },
    { id: 'u4-m3', text: 'Almost done', senderId: 'me', timestamp: '11:10 AM', type: 'text' },
    { id: 'u4-m4', text: 'Great!', senderId: 'user-4', timestamp: '11:15 AM', type: 'text' },
    {
      id: 'u4-m5',
      text: 'Can you send me the link?',
      senderId: 'user-4',
      timestamp: '11:20 AM',
      type: 'text',
    },
    { id: 'u4-m6', text: 'Sure, here it is', senderId: 'me', timestamp: '11:25 AM', type: 'text' },
    { id: 'u4-m7', text: 'Thanks!', senderId: 'user-4', timestamp: '11:30 AM', type: 'text' },
    { id: 'u4-m8', text: 'You are welcome', senderId: 'me', timestamp: '11:35 AM', type: 'text' },
    { id: 'u4-m9', text: 'See you later', senderId: 'user-4', timestamp: '11:40 AM', type: 'text' },
    { id: 'u4-m10', text: 'Bye!', senderId: 'me', timestamp: '11:45 AM', type: 'text' },
  ],
  'user-5': [
    { id: 'u5-m1', text: 'Hi Charlie!', senderId: 'me', timestamp: '12:00 PM', type: 'text' },
    {
      id: 'u5-m2',
      text: 'Did you get the report?',
      senderId: 'user-5',
      timestamp: '12:05 PM',
      type: 'text',
    },
    { id: 'u5-m3', text: 'Not yet', senderId: 'me', timestamp: '12:10 PM', type: 'text' },
    {
      id: 'u5-m4',
      text: 'I will send it now',
      senderId: 'user-5',
      timestamp: '12:15 PM',
      type: 'text',
    },
    { id: 'u5-m5', text: 'Got it, thanks', senderId: 'me', timestamp: '12:20 PM', type: 'text' },
    { id: 'u5-m6', text: 'Any comments?', senderId: 'user-5', timestamp: '12:25 PM', type: 'text' },
    { id: 'u5-m7', text: 'Looks good', senderId: 'me', timestamp: '12:30 PM', type: 'text' },
    { id: 'u5-m8', text: 'Perfect', senderId: 'user-5', timestamp: '12:35 PM', type: 'text' },
    {
      id: 'u5-m9',
      text: 'Let me know if you need anything else',
      senderId: 'user-5',
      timestamp: '12:40 PM',
      type: 'text',
    },
    { id: 'u5-m10', text: 'Will do!', senderId: 'me', timestamp: '12:45 PM', type: 'text' },
  ],
  'user-6': [
    { id: 'u6-m1', text: 'Hello Diana!', senderId: 'me', timestamp: '1:00 PM', type: 'text' },
    {
      id: 'u6-m2',
      text: 'Did you see the news?',
      senderId: 'user-6',
      timestamp: '1:05 PM',
      type: 'text',
    },
    { id: 'u6-m3', text: 'Which one?', senderId: 'me', timestamp: '1:10 PM', type: 'text' },
    {
      id: 'u6-m4',
      text: 'The one about the new release',
      senderId: 'user-6',
      timestamp: '1:15 PM',
      type: 'text',
    },
    { id: 'u6-m5', text: 'Oh, yes I did!', senderId: 'me', timestamp: '1:20 PM', type: 'text' },
    {
      id: 'u6-m6',
      text: 'Exciting, right?',
      senderId: 'user-6',
      timestamp: '1:25 PM',
      type: 'text',
    },
    { id: 'u6-m7', text: 'Definitely!', senderId: 'me', timestamp: '1:30 PM', type: 'text' },
    {
      id: 'u6-m8',
      text: 'We should try it out',
      senderId: 'user-6',
      timestamp: '1:35 PM',
      type: 'text',
    },
    { id: 'u6-m9', text: 'Agreed', senderId: 'me', timestamp: '1:40 PM', type: 'text' },
    {
      id: 'u6-m10',
      text: "Let's do it tomorrow",
      senderId: 'user-6',
      timestamp: '1:45 PM',
      type: 'text',
    },
  ],
  'user-7': [
    { id: 'u7-m1', text: 'Hi Ethan!', senderId: 'me', timestamp: '2:00 PM', type: 'text' },
    {
      id: 'u7-m2',
      text: 'Mission accomplished',
      senderId: 'user-7',
      timestamp: '2:05 PM',
      type: 'text',
    },
    {
      id: 'u7-m3',
      text: 'Wow, that was fast!',
      senderId: 'me',
      timestamp: '2:10 PM',
      type: 'text',
    },
    {
      id: 'u7-m la',
      text: 'I tried my best',
      senderId: 'user-7',
      timestamp: '2:15 PM',
      type: 'text',
    },
    { id: 'u7-m5', text: 'Any complications?', senderId: 'me', timestamp: '2:20 PM', type: 'text' },
    { id: 'u7-m6', text: 'None at all', senderId: 'user-7', timestamp: '2:25 PM', type: 'text' },
    { id: 'u7-m7', text: 'Great job!', senderId: 'me', timestamp: '2:30 PM', type: 'text' },
    { id: 'u7-m8', text: 'Thanks!', senderId: 'user-7', timestamp: '2:35 PM', type: 'text' },
    { id: 'u7-m9', text: 'What is next?', senderId: 'me', timestamp: '2:40 PM', type: 'text' },
    {
      id: 'u7-m10',
      text: 'Next mission awaits',
      senderId: 'user-7',
      timestamp: '2:45 PM',
      type: 'text',
    },
  ],
  'user-8': [
    { id: 'u8-m1', text: 'Hi Fiona!', senderId: 'me', timestamp: '3:00 PM', type: 'text' },
    {
      id: 'u8-m2',
      text: 'Check your email',
      senderId: 'user-8',
      timestamp: '3:05 PM',
      type: 'text',
    },
    { id: 'u8-m3', text: 'Checking now', senderId: 'me', timestamp: '3:10 PM', type: 'text' },
    {
      id: 'u8-m4',
      text: 'Did you find it?',
      senderId: 'user-8',
      timestamp: '3:15 PM',
      type: 'text',
    },
    { id: 'u8-m5', text: 'Yes, I got it', senderId: 'me', timestamp: '3:20 PM', type: 'text' },
    {
      id: 'u8-m6',
      text: 'What do you think?',
      senderId: 'user-8',
      timestamp: '3:25 PM',
      type: 'text',
    },
    { id: 'u8-m7', text: 'It looks promising', senderId: 'me', timestamp: '3:30 PM', type: 'text' },
    { id: 'u8-m8', text: 'I agree', senderId: 'user-8', timestamp: '3:35 PM', type: 'text' },
    {
      id: 'u8-m9',
      text: 'Let me review it carefully',
      senderId: 'me',
      timestamp: '3:40 PM',
      type: 'text',
    },
    {
      id: 'u8-m10',
      text: 'Take your time',
      senderId: 'user-8',
      timestamp: '3:45 PM',
      type: 'text',
    },
  ],
}
